action: save # train or test
name: training multimodal # name of the experiment needed for the logs
modality: ["RGB","EMG"] # modality used
total_batch: 128 # total batch size if training is done with gradient accumulation
batch_size: 32 # batch size for the forward
gpus: null # gpus adopted
wandb_name: null # needed for wandb logging
logname: null # name of the logs
models_dir: saved_models # directory containing all the models
aggregation: True
features_path: [mid_level_features]
split: train


resume_from:  # checkpoint directory
  RGB: saved_models/ActionNet/RGB_model/LSTM_dense_25/model_1/action-classifier_RGB_9.pth
  EMG: saved_models/ActionNet/EMG_model/LSTM/model_1/action-classifier_EMG_9.pth

save:
  num_iter: 5000 # number of training iterations with total_batch size
  lr_steps: 3000 # steps before reducing learning rate
  eval_freq: 50 # evaluation frequency
  num_clips: 5 # clips adopted in training
  spectogram_feat: ??
  dense_sampling: # sampling version adopted in training for each modality
    RGB: True
  num_frames_per_clip: # number of frames adopted in training for each modality
    RGB: ??

test:
  num_clips: 5 # number of clips in testing
  dense_sampling: # sampling version adopted in test for each modality
    RGB: True
  num_frames_per_clip: # number of frames adopted in test for each modality
    RGB: 5

dataset:
  annotations_path: an_multimodal_annotations # path for the annotations data
  shift: S04-S04 # shifts of the dataset
  workers: 4 # number of workers for the dataloader
  stride: 2 # stride in case of dense sampling
  resolution: 224 # input resolution to the model
  num_classes: 20
  RGB:
    data_path: saved_features_an_multimodal # folder to pkl data
    tmpl: "img_{:010d}.jpg" # format of RGB filenames
    features_name: features_rgb # name of the pkl file
  EMG:
    data_path: saved_features_an_multimodal # folder to pkl data
    features_name: features_emg # name of the pkl file
  Event: # not neeeded for the project
    rgb4e: 6

# these are the action recognition models for each modality
models:
  RGB:
    model: ??
    normalize: False
    kwargs: {}
    lr_steps: 3000
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7
  EMG:
    model: ???
    normalize: False
    kwargs: { }
    lr_steps: 3000
    lr: 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7
